'use strict';
const {assert,within,atomic,id}=require('./core.cjs');const {run}=require('./media.cjs');const path=require('node:path');const fs=require('node:fs');
function transcriptPlan(source,words,{padding=.08,maxGap=.6,removeFillers=true}={}){assert(Array.isArray(words)&&words.length>0&&words.length<=50000,'Word-timed transcript required');let last=0;const kept=[];for(const w of words){assert(typeof w.text==='string'&&Number.isFinite(w.start)&&Number.isFinite(w.end)&&w.start>=last&&w.end>w.start,'Invalid word timing');last=w.start;if(removeFillers&&/^(um+|uh+|erm|hmm)[,.!?]?$/i.test(w.text.trim()))continue;kept.push(w);}assert(kept.length,'No speech remains');const clips=[];for(const w of kept){const start=Math.max(0,w.start-padding),end=w.end+padding;if(clips.length&&start-clips.at(-1).end<=maxGap)clips.at(-1).end=end;else clips.push({start,end});}assert(clips.length<=200,'Transcript produces more than 200 clips; split into chapters');return {version:1,source,clips,notes:'Review cuts before rendering. This rule-based proposal removes isolated fillers and long gaps; it does not correct English or identify semantic repetition.',script:kept.map(w=>w.text).join(' ')};}
function srtTime(sec){assert(Number.isFinite(sec)&&sec>=0,'Invalid caption timing');const ms=Math.round(sec*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;}
async function composeNarrated(media,root,segments,options={}){assert(Array.isArray(segments)&&segments.length>0&&segments.length<=40,'Use 1–40 narration segments');const chapterDir='chapters/'+id().slice(0,8);fs.mkdirSync(within(root,chapterDir),{recursive:true});const outputs=[],captions=[];let offset=0;for(const [i,s]of segments.entries()){
 assert(typeof s.text==='string'&&s.text.length<=5000&&Number.isFinite(s.start)&&Number.isFinite(s.end)&&s.end>s.start&&s.start>=0,'Invalid narrated segment');const source=within(root,s.video,true),audio=within(root,s.audio,true),vp=await media.probe(source),ap=await media.probe(audio);assert(s.end<=Number(vp.format.duration)+.05,'Segment exceeds video duration');const duration=Number(ap.format.duration);assert(duration>0&&duration<=600,'Narration segment must be between 0 and 600 seconds');const clipLength=s.end-s.start;const filter=`scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30,tpad=stop_mode=clone:stop_duration=${Math.max(0,duration-clipLength)}`;
 const out=await media.output(root,'chapter',['-ss',String(s.start),'-t',String(clipLength),'-i',source,'-i',audio,'-map','0:v:0','-map','1:a:0','-vf',filter,'-t',String(duration),'-c:v','libx264','-preset','veryfast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-ar','48000','-ac','2'],options);outputs.push(out);captions.push(`${i+1}\n${srtTime(offset)} --> ${srtTime(offset+duration)}\n${s.text.replace(/\r?\n/g,' ')}\n`);offset+=duration;}
  const list=within(root,chapterDir+'/concat.txt');atomic(list,outputs.map(o=>"file '"+within(root,o.file,true).split(path.sep).join('/').replace(/'/g,"'\\''")+"'").join('\n'));
 const output=await media.output(root,'narrated-brief',['-f','concat','-safe','0','-i',list,'-c','copy'],options);const captionsFile=output.file.replace('.mp4','.srt');atomic(within(root,captionsFile),captions.join('\n'));atomic(within(root,output.file.replace('.mp4','.json')),{segments,chapters:outputs,output,captions:captionsFile,note:'Source-speed footage then last-frame hold when narration is longer. Shorter narration trims demonstration. Review completeness. Captions are segment-level, not word-aligned.'});return {...output,captions:captionsFile};}
module.exports={transcriptPlan,composeNarrated,srtTime};
