'use strict';
const fs=require('node:fs');const path=require('node:path');const {EventEmitter}=require('node:events');
const {assert,disk,atomic,now,hash}=require('./core.cjs');
const PROFILE='OBS Companion';const SCENE='Companion · isolated sources';
class Capture extends EventEmitter {
 constructor(store,client){super();this.store=store;this.obs=client||new(require('obs-websocket-js').default)();this.connected=false;this.active=null;this.meters=[];this.timer=null;
  this.obs.on('ConnectionClosed',()=>{this.connected=false;clearInterval(this.timer);if(this.active){this.store.update(this.active,'Interrupted',{error:'OBS disconnected. Recording may still be running in OBS. Reconnect before recovery.'});}this.emit('change');});
  this.obs.on('InputVolumeMeters',e=>{this.meters=e.inputs.filter(i=>i.inputName==='Companion Mic').map(i=>({name:i.inputName,peak:Math.max(...i.inputLevelsMul.flat())}));});
  this.obs.on('RecordStateChanged',e=>{if(this.active){this.store.event(this.active,'obs-record-state',{state:e.outputState,active:e.outputActive,path:e.outputPath||null});if(!e.outputActive&&!this.stopping){this.store.update(this.active,'Interrupted',{error:'Recording stopped outside the companion or encoder failed. Inspect OBS and recover the master.'});clearInterval(this.timer);}}});
 }
 async call(name,data={}){assert(this.connected,'Connect to OBS first');return this.obs.call(name,data);}
 async connect(password,port=4455){assert(typeof password==='string'&&password.length>0,'Set an OBS WebSocket password first');assert(Number.isInteger(port)&&port>=1024&&port<=65535,'Invalid port');await this.obs.connect(`ws://127.0.0.1:${port}`,password,{rpcVersion:1,eventSubscriptions:1|4|8|64|65536});this.connected=true;const version=await this.call('GetVersion');this.version=version;assert(version.availableRequests.includes('SetVideoSettings'),'OBS WebSocket 5.x required');return version;}
 async idle(){const r=await this.call('GetRecordStatus'),s=await this.call('GetStreamStatus');assert(!r.outputActive&&!s.outputActive,'Stop OBS recording/streaming before setup');}
 async setup(){await this.idle();const profiles=await this.call('GetProfileList'),collections=await this.call('GetSceneCollectionList');if(profiles.currentProfileName!==PROFILE&&collections.currentSceneCollectionName!==PROFILE){this.previous={profile:profiles.currentProfileName,collection:collections.currentSceneCollectionName};atomic(path.join(this.store.root,'obs-restore.json'),this.previous);}
  if(!profiles.profiles.includes(PROFILE))await this.call('CreateProfile',{profileName:PROFILE});await this.call('SetCurrentProfile',{profileName:PROFILE});
  if(!collections.sceneCollections.includes(PROFILE))await this.call('CreateSceneCollection',{sceneCollectionName:PROFILE});await this.call('SetCurrentSceneCollection',{sceneCollectionName:PROFILE});
  const scenes=await this.call('GetSceneList');if(!scenes.scenes.some(s=>s.sceneName===SCENE))await this.call('CreateScene',{sceneName:SCENE});
  const kinds=(await this.call('GetInputKindList',{unversioned:true})).inputKinds;
  for(const kind of ['monitor_capture','dshow_input','wasapi_input_capture'])assert(kinds.includes(kind),`Windows OBS source ${kind} unavailable. Use the Windows build of OBS Studio.`);
  const inputs=await this.call('GetInputList');
  for(const [inputName,inputKind] of [['Companion Screen','monitor_capture'],['Companion Camera','dshow_input'],['Companion Mic','wasapi_input_capture'],['Companion Desktop','wasapi_output_capture']])if(!inputs.inputs.some(i=>i.inputName===inputName))await this.call('CreateInput',{sceneName:SCENE,inputName,inputKind,inputSettings:{},sceneItemEnabled:true});
  await this.call('SetCurrentProgramScene',{sceneName:SCENE});
  // Fresh scene collections may inherit global desktop/mic inputs. Explicitly mute all audio except the selected microphone.
  for(const i of (await this.call('GetInputList')).inputs){try{await this.call('SetInputMute',{inputName:i.inputName,inputMuted:i.inputName!=='Companion Mic'});}catch{}}
  await this.call('SetInputAudioTracks',{inputName:'Companion Mic',inputAudioTracks:{'1':true,'2':false,'3':false,'4':false,'5':false,'6':false}});
  return this.devices();
 }
 async devices(){const result={};for(const [key,inputName,propertyName] of [['cameras','Companion Camera','video_device_id'],['microphones','Companion Mic','device_id'],['screens','Companion Screen','monitor_id'],['outputs','Companion Desktop','device_id']]){try{result[key]=(await this.call('GetInputPropertiesListPropertyItems',{inputName,propertyName})).propertyItems.filter(i=>i.itemEnabled);}catch(e){result[key]=[];result[key+'Error']=e.message;}}return result;}
 async configure({camera,microphone,screen,desktop,encoder='obs_x264'}){await this.idle();assert(camera&&microphone&&screen!==undefined,'Select camera, microphone and display');const devices=await this.devices();for(const [key,v] of [['cameras',camera],['microphones',microphone],['screens',screen]])assert(devices[key].some(i=>i.itemValue===v),'Selected device is no longer available');
  const available=this.version.availableRequests.includes('GetEncoderList')?(await this.call('GetEncoderList')).encoders:[];
  if(encoder==='configured'){const current=await this.call('GetProfileParameter',{parameterCategory:'AdvOut',parameterName:'RecEncoder'});assert(current.parameterValue&&current.parameterValue!=='none','Choose a dedicated recording encoder in OBS Output → Advanced first');encoder=current.parameterValue;}else if(encoder!=='obs_x264')assert(available.some(e=>(e.encoderId||e.id)===encoder),'Selected hardware encoder is unavailable');
  await this.call('SetInputSettings',{inputName:'Companion Camera',inputSettings:{video_device_id:camera,res_type:1,resolution:'1920x1080',frame_interval:333333},overlay:true});
  await this.call('SetInputSettings',{inputName:'Companion Mic',inputSettings:{device_id:microphone},overlay:true});
  await this.call('SetInputSettings',{inputName:'Companion Screen',inputSettings:{monitor_id:screen,capture_cursor:true},overlay:true});
  if(desktop){assert(devices.outputs.some(i=>i.itemValue===desktop),'Desktop audio device unavailable');await this.call('SetInputSettings',{inputName:'Companion Desktop',inputSettings:{device_id:desktop},overlay:true});await this.call('SetInputAudioTracks',{inputName:'Companion Desktop',inputAudioTracks:{'1':false,'2':true,'3':false,'4':false,'5':false,'6':false}});}await this.call('SetInputMute',{inputName:'Companion Desktop',inputMuted:!desktop});
  await this.call('SetVideoSettings',{baseWidth:3840,baseHeight:1080,outputWidth:3840,outputHeight:1080,fpsNumerator:30,fpsDenominator:1});
  const settings=[['Output','Mode','Advanced'],['AdvOut','RecType','Standard'],['AdvOut','RecFormat2','mkv'],['AdvOut','RecEncoder',encoder],['AdvOut','RecTracks',desktop?'3':'1'],['AdvOut','RecRescale','false']];
  for(const [parameterCategory,parameterName,parameterValue] of settings)await this.call('SetProfileParameter',{parameterCategory,parameterName,parameterValue});
  for(const [sourceName,x] of [['Companion Screen',0],['Companion Camera',1920]]){const {sceneItemId}=await this.call('GetSceneItemId',{sceneName:SCENE,sourceName});await this.call('SetSceneItemTransform',{sceneName:SCENE,sceneItemId,sceneItemTransform:{positionX:x,positionY:0,alignment:5,boundsType:'OBS_BOUNDS_SCALE_INNER',boundsWidth:1920,boundsHeight:1080,boundsAlignment:0,cropLeft:0,cropRight:0,cropTop:0,cropBottom:0}});}
  const sourceDimensions={};for(const sourceName of ['Companion Screen','Companion Camera']){const {sceneItemId}=await this.call('GetSceneItemId',{sceneName:SCENE,sourceName});const t=(await this.call('GetSceneItemTransform',{sceneName:SCENE,sceneItemId})).sceneItemTransform;sourceDimensions[sourceName]={width:t.sourceWidth,height:t.sourceHeight};}this.config={sourceDimensions,camera,microphone,screen,desktop:desktop||null,encoder,width:1920,height:1080,fps:30};return {video:await this.call('GetVideoSettings'),config:this.config};
 }
 async preview(){const results=await Promise.all(['Companion Screen','Companion Camera'].map(sourceName=>this.call('GetSourceScreenshot',{sourceName,imageFormat:'jpg',imageWidth:768,imageCompressionQuality:75})));return {screen:results[0].imageData,camera:results[1].imageData};}
 async start(pid){assert(!this.active,'A recording requires recovery or completion first');assert(this.config,'Configure and preview devices first');await this.idle();const p=this.store.get(pid);assert(['Ready','Needs Review'].includes(p.state),'Finish or recover the current project operation first');assert(p.mode==='record','Not a recording project');const dir=path.join(this.store.dir(pid),'masters');fs.mkdirSync(dir,{recursive:true});disk(dir,2*1024**3);
  const v=await this.call('GetVideoSettings');assert(v.outputWidth===3840&&v.outputHeight===1080,'OBS output size changed; configure again');
  await this.call('SetRecordDirectory',{recordDirectory:dir});this.store.claim(pid,'Recording',['Ready','Needs Review']);this.active=pid;this.store.update(pid,'Recording',{capture:this.config,started:now(),error:null});
  try{await this.call('StartRecord');const status=await this.call('GetRecordStatus');assert(status.outputActive,'OBS did not start recording');this.store.event(pid,'record-start',status);this.timer=setInterval(()=>this.poll().catch(()=>{}),2000);}catch(e){this.store.update(pid,'Interrupted',{error:'Start not confirmed. Check OBS before retrying.'});throw e;}return this.store.get(pid);
 }
 async poll(){if(!this.active)return;const status=await this.call('GetRecordStatus');const stats=await this.call('GetStats');this.last={...status,...stats};this.emit('change');try{disk(this.store.dir(this.active),256*1024**2);}catch(e){await this.stop();this.store.update(this.lastProject,'Needs Review',{warning:'Stopped early because disk space was low'});}return this.last;}
 async pause(){assert(this.active&&this.store.get(this.active).state==='Recording','Not recording');await this.call('PauseRecord');this.store.update(this.active,'Paused');this.store.event(this.active,'pause',await this.call('GetRecordStatus'));}
 async resume(){assert(this.active&&this.store.get(this.active).state==='Paused','Not paused');await this.call('ResumeRecord');this.store.update(this.active,'Recording');this.store.event(this.active,'resume',await this.call('GetRecordStatus'));}
 async stop(){assert(this.active,'No owned recording');const pid=this.active;this.stopping=true;clearInterval(this.timer);this.store.update(pid,'Stopping');try{const result=await this.call('StopRecord');assert(typeof result.outputPath==='string','OBS did not return the completed filename');const dir=fs.realpathSync(this.store.dir(pid)),file=fs.realpathSync(result.outputPath);assert(file.startsWith(dir+path.sep),'OBS saved outside the expected project; inspect OBS output');assert(fs.statSync(file).size>0,'Recording is empty');const relative=path.relative(dir,file).split(path.sep).join('/');this.store.update(pid,'Needs Review',{master:relative,completed:now(),sourceSha256:await hash(file),error:null});this.active=null;this.lastProject=pid;return this.store.get(pid);}catch(e){this.store.update(pid,'Interrupted',{error:e.message});throw e;}finally{this.stopping=false;}}
 async recover(pid){assert(!this.active||this.active===pid,'Another recording is active');this.store.get(pid);const status=await this.call('GetRecordStatus');assert(!status.outputActive,'OBS is still recording. Stop it in OBS, then recover.');const dir=path.join(this.store.dir(pid),'masters');const files=fs.existsSync(dir)?fs.readdirSync(dir).filter(f=>/\.mkv$/i.test(f)):[];assert(files.length,'No recoverable MKV found');const manifests=[];for(const f of files){const p=path.join(dir,f);manifests.push({file:'masters/'+f,size:fs.statSync(p).size,sha256:await hash(p)});}this.active=null;return this.store.update(pid,'Needs Review',{recovered:manifests,master:manifests.at(-1).file,error:null,warning:'Recovered interrupted MKV. Review audio/video before export.'});}
 async restore(){await this.idle();const prev=this.previous||JSON.parse(fs.readFileSync(path.join(this.store.root,'obs-restore.json'),'utf8'));await this.call('SetCurrentSceneCollection',{sceneCollectionName:prev.collection});await this.call('SetCurrentProfile',{profileName:prev.profile});}
 async close(){clearInterval(this.timer);if(this.active){try{await this.stop();}catch{}}if(this.connected)await this.obs.disconnect();}
}
module.exports={Capture,PROFILE,SCENE};
