const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{EventEmitter}=require('node:events');const{Store}=require('../src/core.cjs');const{Capture}=require('../src/obs.cjs');
// These are protocol-contract mocks, NOT real OBS or Windows evidence.
class Fake extends EventEmitter{constructor(){super();this.calls=[];this.active=false;}async connect(){}async disconnect(){}async call(name,args){this.calls.push({name,args});if(name==='GetVersion')return {availableRequests:['SetVideoSettings'],obsVersion:'mock'};if(name==='GetRecordStatus')return {outputActive:this.active,outputTimecode:'00:00:01.000'};if(name==='GetStreamStatus')return {outputActive:false};if(name==='GetVideoSettings')return {outputWidth:3840,outputHeight:1080};if(name==='SetRecordDirectory'){this.dir=args.recordDirectory;return{}}if(name==='StartRecord'){this.active=true;return{}}if(name==='StopRecord'){this.active=false;const file=path.join(this.dir,'test.mkv');fs.writeFileSync(file,'synthetic protocol fixture, not video');return{outputPath:file}}return {};}}
test('OBS contract: owned record pause/resume stop journals state',async()=>{const s=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'obs-contract-'))),f=new Fake(),c=new Capture(s,f);await c.connect('test-password');c.config={fps:30};const p=s.create('Mock recording','record');await c.start(p.id);await c.pause();assert.equal(s.get(p.id).state,'Paused');await c.resume();await c.stop();assert.equal(s.get(p.id).state,'Needs Review');assert.ok(s.get(p.id).data.sourceSha256);assert.ok(s.events(p.id).some(e=>e.type==='pause'));await c.close();s.close();});
test('OBS contract: disconnect cannot become successful completion',async()=>{const s=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'obs-contract-'))),f=new Fake(),c=new Capture(s,f);await c.connect('test-password');c.config={fps:30};const p=s.create('Disconnected','record');await c.start(p.id);f.emit('ConnectionClosed');assert.equal(s.get(p.id).state,'Interrupted');assert.equal(s.get(p.id).data.completed,undefined);c.active=null;await c.close();s.close();});
test('OBS setup snapshots either changed owner setting and reattaches existing inputs (mock OBS)',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'obs-setup-')),s=new Store(root);
 class SetupFake extends EventEmitter{constructor(){super();this.calls=[];}async call(name,args={}){this.calls.push({name,args});if(name==='GetRecordStatus'||name==='GetStreamStatus')return {outputActive:false};if(name==='GetProfileList')return {currentProfileName:'User profile',profiles:['User profile','OBS Companion']};if(name==='GetSceneCollectionList')return {currentSceneCollectionName:'OBS Companion',sceneCollections:['OBS Companion']};if(name==='GetSceneList')return {scenes:[{sceneName:'Companion · isolated sources'}]};if(name==='GetInputKindList')return {inputKinds:['monitor_capture','dshow_input','wasapi_input_capture','wasapi_output_capture']};if(name==='GetInputList')return {inputs:[{inputName:'Companion Screen'},{inputName:'Companion Camera'},{inputName:'Companion Mic'},{inputName:'Companion Desktop'}]};if(name==='GetSceneItemId'){if(args.sourceName==='Companion Screen'&&!this.reattached)throw Error('missing');return {sceneItemId:1};}if(name==='CreateSceneItem'){this.reattached=true;return {sceneItemId:1};}if(name==='GetInputPropertiesListPropertyItems')return {propertyItems:[]};return {};}}
 const f=new SetupFake(),c=new Capture(s,f);c.connected=true;await c.setup();
 assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'obs-restore.json'),'utf8')),{profile:'User profile',collection:'OBS Companion'});
 assert.ok(f.calls.some(x=>x.name==='CreateSceneItem'&&x.args.sourceName==='Companion Screen'));
 assert.ok(f.calls.some(x=>x.name==='SetSceneItemEnabled'&&x.args.sourceName===undefined));
 c.connected=false;s.close();
});
