'use strict';
const esc = (value = '') => String(value).replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const link = (href,label,cls='',extra='') => `<a href="${esc(href)}" class="${cls}" ${extra}>${esc(label)}</a>`;
const button = (m,location) => link(m.cta.href,m.cta.label,'button primary',`data-cta="${location}"`);
const brand = '<a href="/" class="brand" aria-label="Vistralo home"><img src="/assets/brand/emblem-light.svg" width="28" height="28" alt=""><span>vistralo</span></a>';
function header(m,c) {return `<a class="skip-link" href="#main">Skip to content</a><div id="nav-sentinel" aria-hidden="true"></div><header class="nav"><div class="container nav-inner">${brand}<nav aria-label="Main">${link('/#how-it-works',c.nav.how)}${link('/#pricing',c.nav.pricing)}${link('/docs/',c.nav.docs)}</nav><details class="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation">${link('/#how-it-works',c.nav.how)}${link('/#pricing',c.nav.pricing)}${link('/docs/',c.nav.docs)}${link('/studio/',c.nav.login)}</nav></details><div class="nav-actions"><a href="#pricing" class="button ghost story-skip" hidden aria-label="${esc(c.story.skipLabel)}">${esc(c.nav.skip)}</a>${link('/studio/',c.nav.login,'login')}${button(m,'navigation')}</div></div></header>`;}
function footer(){return `<footer class="container footer"><div class="footer-top">${brand}<div class="footer-column"><h2>Product</h2>${link('/#how-it-works','How it works')}${link('/#pricing','Pricing')}${link('/changelog/','Changelog')}${link('/studio/','Log in')}</div><div class="footer-column"><h2>Resources</h2>${link('/docs/','Docs')}${link('/reference/fernhill/','Reference site')}${link('mailto:contact@vistralo.com','Support')}</div><div class="footer-column"><h2>Company</h2>${link('/about/','About')}${link('mailto:contact@vistralo.com','Contact')}</div><div class="footer-column"><h2>Legal</h2>${link('/privacy/','Privacy')}${link('/terms/','Terms')}${link('/security/','Security')}</div></div><div class="footer-bottom"><span>© 2026 Vistralo</span><span>Dynamix LTD · Dhaka, Bangladesh</span></div></footer>`;}
function picture(scene,first=false) {return `<picture><source media="(max-width: 600px)" srcset="${esc(scene.mobilePoster)}"><img src="${esc(scene.desktopPoster)}" width="1280" height="800" alt="${esc(scene.title)}" ${first?'fetchpriority="high"':'loading="lazy"'} decoding="async"></picture>`;}
function compare(m,c) {return `<div class="compare" data-compare><div class="compare-images"><img src="${esc(m.compare.original)}" alt="${esc(c.story.original)}" width="1280" height="800"><img class="compare-after" src="${esc(m.compare.rebuilt)}" alt="${esc(c.story.rebuilt)}" width="1280" height="800"><span class="compare-rule" aria-hidden="true"></span></div><div class="compare-labels"><span>${esc(c.story.original)}</span><span>${esc(c.story.rebuilt)}</span></div><label>${esc(c.story.compare)}<input aria-label="${esc(c.story.compare)}" type="range" min="0" max="100" step="2" value="50"></label></div>`;}
function story(m,c,opening='') {
 const scenes=m.scenes.filter(s=>s.enabled);
 if(!scenes.length)return '';
 const hasNarration=scenes.some(s=>s.id==='observe')&&m.narration.approved&&m.narration.mp4;
 const hasCompare=scenes.some(s=>s.id==='build')&&m.compare.uneditedAgentOutput&&m.compare.original;
 return `<section id="how-it-works" class="story container" aria-label="Vistralo walkthrough"><div class="story-pin ${opening?'has-opening':''}">${opening}<div class="hero-stage-slot" aria-hidden="true"></div><div class="story-heading" aria-hidden="true"><p class="scene-number"></p><h2></h2><p class="scene-support"></p></div><div id="stage" role="region" aria-label="Product walkthrough"><div class="stage-poster">${picture(scenes[0],true)}</div><canvas class="frames" role="img" aria-label="${esc(scenes[0].title)}"></canvas><svg class="callouts" viewBox="0 0 1280 800" aria-hidden="true"></svg><div class="stage-compare" hidden>${hasCompare?compare(m,c):''}</div><div class="judgment-wipe" hidden><p class="generic-caption">${esc(m.genericCaption||'')}</p><p class="specific-caption"></p><div class="judgment-controls"><button type="button" data-judgment="0" aria-pressed="false">${esc(c.story.generic)}</button><button type="button" data-judgment="1" aria-pressed="true">${esc(c.story.vistralo)}</button></div></div></div><div class="caption-strip"><span class="timecode" aria-hidden="true"></span><div class="captions"></div>${hasNarration?`<button class="button listen" type="button">${esc(c.story.listen)}</button>`:''}</div><div class="story-progress" aria-hidden="true"><span></span></div></div><div class="story-transcript">${scenes.map((s,i)=>`<section class="static-scene" id="scene-${esc(s.id)}"><p class="scene-number">${String(i+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}</p><h2>${esc(s.title)}</h2><p>${esc(s.support)}</p>${picture(s)}${s.id==='judgment'&&m.genericCaption?`<p>Generic AI narration: ${esc(m.genericCaption)}</p>`:''}${s.callouts.map(callout=>`<p class="static-callout">${esc(callout.label)}</p>`).join('')}${s.captions.map(x=>`<p>${esc(x.text)}</p>`).join('')}</section>`).join('')}</div></section>${hasCompare?`<section class="container static-compare"><h2>${esc(c.story.compare)}</h2>${compare(m,c)}</section>`:''}${hasNarration?`<section class="container narration-fallback"><h2>Narrated walkthrough</h2><video controls preload="none" poster="${esc(scenes.find(x=>x.id==='observe')?.desktopPoster||scenes[0].desktopPoster)}">${m.narration.webm?`<source src="${esc(m.narration.webm)}" type="video/webm">`:''}<source src="${esc(m.narration.mp4)}" type="video/mp4"><track default kind="captions" srclang="en" label="English" src="${esc(m.narration.vtt)}"></video><p>${link(m.narration.transcript,'Read the narration transcript')}</p></section><dialog id="narration" aria-labelledby="narration-title"><div class="dialog-header"><h2 id="narration-title">Narrated walkthrough</h2><button class="button close-dialog">${esc(c.story.close)}</button></div><div class="video-slot"></div><p class="video-error" hidden>${esc(c.story.videoError)}</p>${link(m.narration.transcript,'Read the narration transcript')}</dialog>`:''}`;
}
function shell({body,title,description,m,c,assets,release=false,page='home'}){return `<!doctype html><html lang="en" data-theme="${page==='home'?'dark':'light'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0B0D12"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${release?'<link rel="canonical" href="https://vistralo.com/'+(page==='home'?'':page+'/')+'">':'<meta name="robots" content="noindex,nofollow">'}<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><link rel="icon" href="/assets/brand/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/inter-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${assets.css}"><script type="module" src="${assets.js}"></script></head><body>${header(m,c)}${body}${footer()}</body></html>`.replaceAll('/assets/brand/emblem-light.svg',page==='home'?'/assets/brand/emblem-light.svg':'/assets/brand/emblem-dark.svg');}
function renderHome({m,c,assets,release}){
 const scenes=m.scenes.filter(s=>s.enabled);
 const heroVisual=scenes.length?`<div class="hero-product">${picture(scenes[0],true)}</div>`:`<div class="reference-window"><div class="reference-bar"><span>Reference site</span><a href="/reference/fernhill/">Open Fernhill Goods</a></div><iframe title="Fernhill Goods, an original reference site for capture testing" src="/reference/fernhill/?embed=1" tabindex="-1" aria-hidden="true" loading="eager" inert></iframe><div class="reference-caption">Your starting point. An original site built for capture testing.</div></div>`;
 const workflow=`<section id="${scenes.length?'workflow':'how-it-works'}" class="container section workflow"><div class="section-intro"><h2>${esc(c.workflow.title)}</h2><p>${esc(c.workflow.support)}</p></div><div class="workflow-grid">${c.workflow.steps.map(x=>`<article><span class="step-number">${x.number}</span><h3>${esc(x.title)}</h3><p>${esc(x.copy)}</p></article>`).join('')}</div><a class="text-link" href="/docs/">Read the capture guide</a></section>`;
 const pricing=m.pricing.approved?`<section id="pricing" class="container section" tabindex="-1"><h2>Simple pricing.</h2><div class="plans">${m.pricing.plans.map(p=>`<article class="plan"><h3>${esc(p.name)}</h3><p class="price">${esc(p.currency)} ${esc(p.amount)} <span>/ ${esc(p.period)}</span></p><ul>${p.inclusions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${link(p.href,'Choose plan','button primary','data-cta="pricing"')}</article>`).join('')}</div></section>`:`<section id="pricing" class="container section access-section" tabindex="-1"><div><p class="section-label">Access & pricing</p><h2>${esc(c.pricing.title)}</h2><p>${esc(c.pricing.support)}</p></div><div class="access-action">${link(m.cta.href,c.pricing.cta,'button primary','data-cta="pricing"')}<p>${esc(c.pricing.note)}</p></div></section>`;
 const opening=`<div class="story-opening hero-copy"><p class="hero-label">${esc(c.hero.label)}</p><h1>${esc(c.hero.title)}</h1><p class="hero-support">${esc(c.hero.support)}</p><div class="hero-actions">${button(m,'hero')}${link('#scene-observe',c.hero.secondary,'button secondary')}</div><p class="hero-note">${esc(c.hero.footnote)}</p></div>`;
 const body=`<main id="main" tabindex="-1">${scenes.length?story(m,c,opening):`<section class="container hero"><div class="hero-copy"><p class="hero-label">${esc(c.hero.label)}</p><h1>${esc(c.hero.title)}</h1><p class="hero-support">${esc(c.hero.support)}</p><div class="hero-actions">${button(m,'hero')}${link('#how-it-works',c.hero.secondary,'button secondary')}</div><p class="hero-note">${esc(c.hero.footnote)}</p></div><div class="hero-visual">${heroVisual}</div></section>`}${workflow}${pricing}<section class="container section faq"><div class="section-intro"><p class="section-label">A few things to know</p><h2>Before your first capture.</h2></div><div class="faq-items">${c.faq.map((x,i)=>`<details name="faq" data-question="${i}"><summary>${esc(x.question)}<span aria-hidden="true">+</span></summary><p>${esc(x.answer)}</p></details>`).join('')}</div></section><section class="container section closing"><h2>${esc(c.closing.title)}</h2><p>${esc(c.closing.support)}</p>${button(m,'closing')}</section></main>`;
 return shell({body,title:c.title,description:c.description,m,c,assets,release});
}
const pages={
 docs:{title:'Capture a reference. Write a useful handoff.',intro:'A guide to the current Vistralo workflow.',sections:[['1. Get access','Sign in with the account provided by your Vistralo administrator. Public self-service registration is not currently available.'],['2. Choose your reference','Use a public website you are authorized to capture. Start with the original Fernhill Goods reference site to explore the workflow. Select your viewport and capture scope.'],['3. Read the coverage notes','Captured frames, visible styles and observed behavior are evidence. A capture can miss interactions, restricted pages or off-screen states. Review those limits before drawing conclusions.'],['4. Edit and share','Review the Markdown brief in your project. Edit its text, download it, or create an expiring read-only link for the selected output. Anyone with a shared link can view that output until expiry or revocation.'],['5. Build with your team','Pass the reviewed brief and reference frames to your team. Automatic website building and named coding-agent integrations are not verified launch features.'],['Narration and AI analysis','The cloud workspace does not currently offer provider narration or AI visual analysis. Optional local provider adapters require credentials and a reviewed job budget. They are not included in this demonstration.']]},
 about:{title:'A clearer handoff from reference to implementation.',intro:'Vistralo is developed by Dynamix LTD.',sections:[['The work','Vistralo brings browser capture evidence and an editable brief into one workflow. It is intended for teams who want to describe an interface precisely before they build.'],['Contact','contact@vistralo.com · Dhaka 1216, Bangladesh.']]},
 privacy:{title:'How project access works.',intro:'Product data information for the current invitation-only workspace. This is not a finalized privacy policy.',sections:[['Project access','Cloud project data is restricted to the owning account. Media is stored privately.'],['Sharing','Creating a read-only link grants access to the selected output to anyone who has that link. Links can expire or be revoked. Other project files and job history are not intentionally included.'],['Capture content','A captured website may contain personal or confidential information. Review your source material and output before sharing.'],['Policy and data requests','A reviewed privacy policy, retention schedule and provider disclosures are still launch requirements. Contact contact@vistralo.com for access and data questions before using the service with personal information.']]},
 terms:{title:'Service terms are being prepared.',intro:'Public subscription plans and customer terms have not been announced.',sections:[['Access','Current access is arranged directly with Dynamix LTD. Contact contact@vistralo.com to discuss your intended use and applicable terms.'],['Reference material','Use material you are authorized to capture and share. A brief is not permission to reuse someone else’s copy, images or branding.']]},
 security:{title:'Security in the current workspace.',intro:'Verified implementation details, with outstanding release work stated explicitly.',sections:[['Private by default','The cloud adapter uses authenticated, owner-isolated project data and private media storage. Selected outputs can be shared using expiring, revocable links.'],['Capture boundaries','Website capture limits private-network access and reports coverage limitations. Provider credentials belong in the server environment, not in a project or brief.'],['Report a concern','Email contact@vistralo.com with a description. Do not include access tokens, passwords or private recordings.'],['Release status','Production acceptance, provider tests, approved legal disclosures and the public marketing recording remain incomplete. This page is not a compliance certification.']]},
 changelog:{title:'What is available.',intro:'Current implementation · 25 September 2026',sections:[['Workspace','Project organization, public website capture, editable Markdown briefs, media review and selected-output share links.'],['Still being verified','The narrated walkthrough, whole-site coding-agent rebuild, brand-token changes and self-service trial described in the marketing brief are not available in this release.']]}
};
function renderPage(page,options){const p=pages[page];return shell({...options,page,title:p.title+' — Vistralo',description:p.intro,body:`<main id="main" tabindex="-1" class="container article"><a class="text-link" href="/">← Back to Vistralo</a><h1>${esc(p.title)}</h1><p class="article-lead">${esc(p.intro)}</p>${p.sections.map(([h,b])=>`<section><h2>${esc(h)}</h2><p>${esc(b)}</p></section>`).join('')}<a class="button secondary" href="mailto:contact@vistralo.com">Contact Vistralo</a></main>`});}
module.exports={renderHome,renderPage,pages};
